Automated code format.

diff --git a/experimental/smith/driver/mkerros b/experimental/smith/driver/mkerros
--- a/experimental/smith/driver/mkerros
+++ b/experimental/smith/driver/mkerros
@@ -1,4 +1,5 @@
 #!/usr/bin/env bash
+
 set -eu
 
 usage() {
@@ -32,24 +33,24 @@ main() {
     # Pattern patch the error file schema. This will strip any gumpf
     # that made it in there.
     grep -E '^[a-zA-Z0-9_\.-]+\.cl,[0-9]+,E_[A-Z_]+,[a-zA-Z0-9_\.-]+$' \
-         $errors_path > $errors_path.tmp || true
+ $errors_path > $errors_path.tmp || true
     mv $errors_path.tmp $errors_path
 
     local nresults=$(wc -l $results_path $errors_path | tail -n1 \
-                            | awk '{print $1}')
+ | awk '{print $1}')
 
     local errors=$(cut -d',' -f 3 < $errors_path | sort | uniq -c \
-                          | sort -rn | awk '{OFS=","; print $2,$1}')
-    ( \
-        echo "Error Frequency Ratio"; \
-        for error in $errors; do
-            local type=$(echo $error | cut -d',' -f1)
-            local count=$(echo $error | cut -d',' -f2)
-            local ratio=$(echo "($count / $nresults) * 100" | bc -l \
-                                 | xargs printf "%.1f%%")
+ | sort -rn | awk '{OFS=","; print $2,$1}')
+    (\
+ echo "Error Frequency Ratio"; \
+ for error in $errors; do
+        local type=$(echo $error | cut -d',' -f1)
+        local count=$(echo $error | cut -d',' -f2)
+        local ratio=$(echo "($count / $nresults) * 100" | bc -l \
+ | xargs printf "%.1f%%")
 
-            echo "$type $count $ratio"
-        done
-    ) | column -t
+        echo "$type $count $ratio"
+    done) | column -t
 }
+
 main $@
